%LET SEED = 1235;
%LET NREP = 1000;

%LET N =  50 100 200;

/* REGRESSION COEFS */
%LET BETA_10 =  3; %LET BETA_11 = -3;
%LET BETA_20 =  4; %LET BETA_21 = -2; %LET BETA_22 = -2;

/* N(0, 1) */
%LET MU    = 0;
%LET SIGMA = 1;

/* GAMMA(0.5, 1) */
%LET SHAPE = 0.5;

/* 0.9 N(0, 2) & 0.1 N(20, 5)  */
%LET MU_1    =  0; %LET SIGMA_1 =  2;
%LET MU_2    = 20; %LET SIGMA_2 =  5;
%LET RATIO = 0.9;

/* UNIFORM(-5, 5) */
%LET A = -5;
%LET B =  5;

%MACRO GENERATE(N, DISTRIBUTION, RETURN_DATA);
	DATA &RETURN_DATA;
		CALL STREAMINIT(&SEED);
		%IF &DISTRIBUTION = "NORMAL" %THEN %DO;
			DO I = 1 TO &N;
				X = RAND ("NORMAL", &MU, &SIGMA);
				OUTPUT;
			END;
		%END;
		%ELSE %IF &DISTRIBUTION = "GAMMA" %THEN %DO;
			DO I = 1 TO &N;
				X = RAND ("GAMMA", &SHAPE) - &SHAPE;
				OUTPUT;
			END;
		%END;
		%ELSE %IF &DISTRIBUTION = "CONTAMINATED_NORMAL" %THEN %DO;
			DO I = 1 TO &N;
				IF I <= &RATIO*&N THEN
					X = RAND ("NORMAL", &MU_1, &SIGMA_1);
				ELSE
					X = RAND ("NORMAL", &MU_2, &SIGMA_2);
				END;
				OUTPUT;
			END;
		%END;
		%ELSE %IF &DISTRIBUTION = "UNIFORM" %THEN %DO;
			DO I = 1 TO &N;
				X = RAND ("UNIFORM", &A, &B);
				OUTPUT;
			END;
		%END;
		DROP I;
	RUN;
%MEND

%MACRO REPLICATE(N, DISTRIBUTION, NREP);
	/* GENERATE DATA FOR EACH DISTRIBUTION */
	%GENERATE(&N, &DISTRIBUTION, X_TEMP);
	
	/* CALCULATE BERNOUILLI RESPONSE */
	DATA TEMP_DATA;
		SET X_TEMP;
		ETA = &BETA_10 + &BETA_11 * X;
		PROB = EXP (ETA) / (1 + EXP (ETA));
		Y = RAND ("BERNOULLI", PROB);
	RUN;

	/* FIT LOGREG */
	PROC LOGISTIC DATA = TEMP_DATA NOPRINT;
		MODEL Y = X;
		ODS OUTPUT PARAMETERESTIMATES = PE_TEMP;
	RUN;

	/* EXTRACT ESTIMATES */
	DATA PE_FORMATTED;
		SET PE_TEMP;
		REPLICATIONS = &NREP;
		SAMPLE_SIZE = &N;
		
		IF VARIABLE = "Intercept" THEN DO;
			BETA_0_EST = ESTIMATE;
			OUTPUT;
		END;
		ELSE IF VARIABLE = "X" THEN DO;
			BETA_1_EST = ESTIMATE;
			OUTPUT;
		END;
	RUN;

	PROC TRANSPOSE DATA = PE_FORMATTED OUT = PE_ROWS PREFIX = BETA;
		BY REPLICATIONS SAMPLE_SIZE;
		ID VARIABLE;
		VAR ESTIMATE;
	RUN;

	DATA PE_FINAL;
		SET PE_ROWS;
		BETA_0_EST = BETAINTERCEPT;
		BETA_1_EST = BETAX;
		KEEP REPLICATIONS SAMPLE_SIZE BETA_0_EST BETA_1_EST;
	RUN

	PROC APPEND BASE = MC_RESULTS DATA = PE_FINAL FORCE;
	RUN;

	PROC DATASETS LIBRARY = WORK NOLIST;
		DELETE X_TEMP TEMP_DATA PE_TEMP PE_FORMATTED PE_ROWS PE_FINAL;
	RUN;
	
%MEND;
